### PR TITLE
Determine "current" stat sensor value based on if workout is in progress, calculate end time using duration if same as start time

### LINKED ISSUE #86: End Time always = Start Time during workout
The end time is always the start time during a workout. Therefore there's no way of displaying the actual estimated end time allowing for any pauses.

If there's no pause (almost always the case), then start time plus duration works nicely - and that's what I'm using at the moment.

Why this is important: my wife likes to know when I'll be done without coming in and disturbing my mojo. 😁

### LINKED ISSUE #90: Current values/sensors don't drop to zero when not in use
I don't know if this is a problem on my end, or just how the sensors work, but sensors like current cadence/resistance/heart rate/speed don't zero out when a workout isn't in progress/running. What ever the final value was of the workout, is the persistent value until you workout again.

### PR DESCRIPTION
**Pull request by RobertD502**
## Overview

* The stat sensors dealing with "current" measurements (`Heart Rate: Current`, `Resistance: Current`, `Speed: Current`, `Cadence: Current`) will now return a value of `0` or, in the case of the speed sensor, `0.0` if a workout is not in progress.
* For the `End Time` sensor, if the API response defines an end time that is equal to the start time and a duration value exists, the end time will be calculated as `start time + duration`. Otherwise, if the end time is not defined in the API response or once the end time differs from the start time, the end time sensor will return a value of `None` or the `end time defined in the API response`, respectively.

## Code Changes

* `workout_in_progress` variable added: This boolean variable is used by the "current" stat sensors to determine what to set their states to depending on if a workout is in progress. If a workout is in progress, these sensors will use the values from the API response. Otherwise, the states of these sensors will be set to `0` when a workout is not in progress.
* Added `calculate_end_time` function: Function used by the `End Time` sensor to determine if the state should be calculated using `start time + duration` or use the end time defined in the API response. 
* State logic for `Start Time`, `End Time`, and `Duration` sensors has been moved to pre-defined variables: The `End Time` sensor now uses the `calculate_end_time` function, which takes a start_time, end_time, and workout_duration. By manipulating and storing the API response values for start time, end time, and duration in variables, it allows us to easily access those values when calling the `calculate_end_time` function from within the `End Time` sensor code.

## Closes:
- Closes #86
- Closes #90

### CODE REVIEW

**Comment by edwork** [comment]
Looks good, I'll do some quick tests and draft a new release. Thanks again!

**Comment by RobertD502** [comment]
Of course, not a problem at all! I see that there is also a need for a reauth flow...perhaps I can look into getting that added as well before you create a release (just so you aren't making multiple releases)?

**Comment by edwork** [comment]
Please feel free to work on that, your contributions are all incredible! Thanks again!

**Comment by RobertD502** [comment]
Well, I got it all implemented, but of course peloton is having issues so I haven't been able to fully test the reauth flow since their login system is down and doesn't even work with my correct password 😑.

**Pull request merged**
