### PR TITLE
v0.8

### PR DESCRIPTION
**Pull request by elahd**
**New Features:**

1. Added support for configuration via Home Assistant UI.
2. Broke out attributes into their own sensors using HA core sensor types and units of measurement where sensible.
3. api_debug.py dumps additional endpoints.
4. Changed integration name to "Peloton" since this is no longer just a single sensor.

**Bug Fixes:**

1. Fixed broken hassfest validation. (hass.json is basically deprecated and only needs a name now.)
2. Fixed exceptions when some workout attributes can't be found.

**HA/HACS Compliance:**

1. Removed info.md. This has been deprecated in HACS. Releases should be made using GitHub's releases feature. HACS will extract version numbers and release notes from there.
2. Added [mypy](http://mypy-lang.org/) static typing to everything.
3. Added Home Assistant's [plugins](https://github.com/home-assistant/core/tree/dev/pylint/plugins) for [pylint](https://pypi.org/project/pylint/). (... and a script that automatically updates the plugins when the Change Home Assistant Version VS Code task is run (see below).
4. Added dependabot and CodeQL GitHub workflows.

**Developer Comfort:**

1. Added ludeeus' [Home Assistant development container](https://github.com/ludeeus/container) to make development in a GitHub / VS Code [codespace](https://github.com/features/codespaces) easier. When opened in a Codespace, this container will automatically install a Home Assistant development environment, will install python dependencies, and will include extensions and tools to make developing an integration easier.
2. Added .yamllint, pyproject.toml, bandit.yaml, and .flake8 config files to enforce coding standards used in Home Assistant's core.
3. Added [pre-commit](https://pre-commit.com/) integration to run code checks before git push.
4. Included VS Code [tasks](https://code.visualstudio.com/Docs/editor/tasks) to make starting Home Assistant and running code checks easier. (Ctrl+Shift+P or Cmd+Shift+P > Run Tasks > Run Pre-Commit Checks / Run Home Assistant / Change Home Assistant Version.

**Omitted:**

I didn't create a migration script from configuration.yaml to the interface-based config. This entire release is a breaking change, so all entity names will change, anyway. I can add to this PR if you'd like.

**Screenshots:**

image

image

image

### CODE REVIEW

**Comment by edwork** [comment]
Incredible amount of detail in this pr - ascii art in const.py!!!

I'll rebase this into the project and as you mentioned, as a breaking change I think it makes sense to have users re-initialize the integration from scratch. 

Thanks for taking the time to make this happen, within a day I should have time to fully test and draft up a new release for HACS.

**Comment by elahd** [comment]
Thanks! Let me know if anything doesn't check out during testing.

**Comment by elahd** [comment]
@edwork Thanks for merging. Will you create a release for this?

**Comment by edwork** [comment]
Yes, worked well as expected for me over the weekend. Drafting the release now!

**Comment by edwork** [comment]
Released!

https://github.com/edwork/homeassistant-peloton-sensor/releases/tag/0.8

**Comment by elahd** [comment]
Thanks!

**Comment by jd3073** [comment]
This is incredible! Great hob elahd!!!
One question - I've removed/re-installed/done everything I can imagine but still do not get the sensors you do.  Here's my screen after HACS installing the repository.
Any guidance on steps to take to get same screen results as your showing?
With respect & appreciation,
John


Screen Shot 2022-07-01 at 2 18 48 PM
Screen Shot 2022-07-01 at 2 39 46 PM

**Comment by edwork** [comment]
HACS creates entities for each integration, allowing you to create automations such as notify when updates are available or group onto a card for admin reasons. It looks like you are looking at this entity. 

With the latest release you'll need to go into the devices and integrations menu and set the sensor back up. This will walk you through an UI setup and create a set of new entities, with the primary entity now being a binary_sensor. 

See if this works and please let us know how it goes. Thanks for using the integration!

Cheers

**Comment by jd3073** [comment]
Edwork - THANK YOU so very much!  Yes, your guidance did the trick.  Thanks again for the very quick and accurate response.  
Thank you for making this integration - it's AWESOME!
John

**Pull request merged**
